version: '3.7'

services:
    reverse-proxy:
        image: nginx:latest
        container_name: reverse-proxy
        volumes:
            -   ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
    petwork-api:
        image: 888002190420.dkr.ecr.eu-west-3.amazonaws.com/petwork-api
        container_name: petwork-api
        environment: 
            - MONGO_DB_URL=${MONGO_DB_URL}
            - SENDIN_BLUE_API_KEY=${SENDIN_BLUE_API_KEY}